export const users = [
  {
    fullName: 'Saim Hashmi',
    preferredName: 'Saim Hashmi',
    pronouns: 'He/Him',
    year: 3,
    program: 'Computer Systems Engineering',
    university: 'Carleton University',
    username: 'anakafeel',
    linkedin: 'http://linkedin.com/in/saim-hashmi-2230b6243',
    github: 'http://github.com/anakafeel',

    website: 'http://saimhashmi.tech',
    instagram: 'http://instagram.com/anakafeel',
    allergies: '',
    phone: '+1-(343)-558-3045',
    tshirtSize: 'M',
  },
  {
    fullName: 'Zesan Rahim',
    preferredName: 'Zesan Rahim',
    pronouns: '',
    year: '',
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'cheeno.',
    linkedin: 'http://linkedin.ca/in/zesanrahim',
    github: 'http://github.com/cheenoxd',

    website: 'http://zesanrahim.com',
    instagram: 'http://instagram.com/zesanrahim',
    allergies: '',
    phone: '+1-(289)-689-0284',
    tshirtSize: 'L',
  },
  {
    fullName: 'Mumtahin Farabi',
    preferredName: 'Mumtahin Farabi',
    pronouns: 'He/Him',
    year: 2,
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'farabi.json',
    linkedin: 'https://www.linkedin.com/in/mfarabi/',
    github: 'https://github.com/mfarabi619',

    website: 'https://mfarabi.dev/',
    instagram: 'http://instagram.com/farabi.01/',
    allergies: 'Dust/Pollen',
    phone: '+6136019872',
    tshirtSize: 'S',
  },
  {
    fullName: 'Adam Said',
    preferredName: 'Adam Said',
    pronouns: '',
    year: '',
    program: '',
    university: 'University of Ottawa',
    username: '',
    linkedin: 'http://linkedin.ca/in/',
    github: 'http://github.com/',

    website: 'http://adam.com',
    instagram: 'http://instagram.com/',
    allergies: '',
    phone: '+1-(###)-###-####',
    tshirtSize: 'XL',
  },
  {
    fullName: 'Esra Abdulwahab',
    preferredName: '',
    pronouns: '',
    year: '',
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'ezbukits',
    linkedin: 'https://www.linkedin.com/in/esra-abdulwahab-947b332ab/',
    github: '',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Jowi Aoun',
    preferredName: 'Jowi',
    pronouns: '',
    year: '',
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'jaythemafia',
    linkedin: 'https://www.linkedin.com/in/jowiaoun/',
    github: 'https://github.com/JowiAoun',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Muhammad Maisam',
    preferredName: 'Maisam',
    pronouns: 'He/Him',
    year: 3,
    program: 'Software Engineering',
    university: 'Carleton University',
    username: 'muhammadmaisam',
    linkedin: 'https://linkedin.com/in/muhammadmaisam01',
    github: 'https://github.com/muhammadmaisam',

    website: 'http://muhammadmaisam.github.io',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '3',
  },
  {
    fullName: 'Bashar Kazma',
    preferredName: '',
    pronouns: '',
    year: '',
    program: 'Computer Science',
    university: '',
    username: 'ba15548',
    linkedin: 'https://www.linkedin.com/in/bashar-k-a7223b208/',
    github: '',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Trista Wang',
    preferredName: 'Trista Wang',
    pronouns: 'She/Her',
    year: 3,
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'TristaWang',
    linkedin: 'https://www.linkedin.com/in/tristaxwang/',
    github: 'https://github.com/TristaWo',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Raef Sarofiem',
    preferredName: 'Raef Sarofiem',
    pronouns: '',
    year: '',
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'justraef',
    linkedin: 'https://www.linkedin.com/in/raefsarofiem/',
    github: '',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Sheila Sieyoji',
    preferredName: 'Sheila Sieyoji',
    pronouns: '',
    year: '',
    program: '',
    university: '',
    username: 'sheila_binkss',
    linkedin: 'https://www.linkedin.com/in/sheila-sieyoji-3b06b52b6/',
    github: '',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Avantika Rao',
    preferredName: 'Avantika Rao',
    pronouns: '',
    year: '',
    program: 'Industrial Design',
    university: 'Carleton University',
    username: 'avantikarao_79644',
    linkedin: 'https://www.linkedin.com/in/avantika-rao-01a1b2204/',
    github: '',

    website: '',
    instagram: '',
    allergies: '',
    phone: '343',
    tshirtSize: '',
  },
  {
    fullName: 'Hasith De Alwis',
    preferredName: 'Hasith De Alwis',
    pronouns: 'he/him',
    year: '2nd',
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'pasta.man',
    linkedin: 'https://www.linkedin.com/in/hasith-de-alwis/',
    github: 'https://github.com/HasithDeAlwis',
    website: 'https://hasithdev.com',
    instagram: 'https://instagram.com/hasith_101',
    allergies: [],
    phone: '3432546633',
    tshirtSize: '',
  },
  {
    fullName: 'Akshavi Baskaran',
    preferredName: 'Akshavi Baskaran',
    pronouns: '',
    year: '',
    program: 'Software Engineering',
    university: 'Carleton University',
    username: 'akshavi',
    linkedin: 'https://www.linkedin.com/in/akshavibaskaran/',
    github: '',
    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Joel Cherian',
    preferredName: 'Joel Cherian',
    pronouns: '',
    year: '',
    program: 'Computer Science',
    university: '',
    username: 'syphxn',
    linkedin: 'https://www.linkedin.com/in/joel-v-cherian',
    github: 'https://github.com/syphxn',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Rayhaan Farooq',
    preferredName: 'Rayhaan',
    pronouns: '',
    year: '',
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'farozen.',
    linkedin: 'https://www.linkedin.com/in/rayhaanfarooq/',
    github: '',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Ishar Ghura',
    preferredName: 'Ishar Ghura',
    pronouns: '',
    year: '',
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'thatfisher',
    linkedin: 'https://www.linkedin.com/in/ishar-ghura/',
    github: 'https://github.com/isharghura',

    website: 'https://isharghura.com',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Ngan Cao',
    preferredName: 'Ngan',
    pronouns: 'She/Her',
    year: 3,
    program: 'Information Resource Management',
    university: 'Carleton University',
    username: 'meemawmoo',
    linkedin: 'http://www.linkedin.com/in/nganc',
    github: '',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Lily Salem',
    preferredName: 'Lily Salem',
    pronouns: '',
    year: '',
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'lil_e.',
    linkedin: '',
    github: '',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Aashna Verma',
    preferredName: 'AASH V',
    pronouns: '',
    year: '',
    program: 'Software Engineering',
    university: 'Carleton University',
    username: 'crying_potatoes',
    linkedin: 'https://www.linkedin.com/in/aashna-verma-000/',
    github: 'https://github.com/Aashna-Verma',
    website: 'https://aashna-verma.github.io/',
    instagram: 'http://instagram.com/',
    allergies: '',
    phone: '+1-(###)-###-####',
    tshirtSize: '',
  },
  {
    fullName: 'Isabella Nguyen',
    preferredName: 'Isabella',
    pronouns: '',
    year: '',
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'inguy',
    linkedin: 'https://www.linkedin.com/in/isabella-vi-nguyen/',
    github: 'https://github.com/Isabella-Nguyen',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Muskaan Opel',
    preferredName: 'Muskaan O.',
    pronouns: '',
    year: '',
    program: 'Chemical and Biological Engineering',
    university: '',
    username: 'muskie0099',
    linkedin: 'https://www.linkedin.com/in/muskaan-opel/',
    github: '',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Khy Browne',
    preferredName: 'Khyonc Browne',
    pronouns: 'She/Her',
    year: 4,
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'khy.cinnamonbun',
    linkedin: '',
    github: '',

    website: '',
    instagram: '',
    allergies: 'Kiwi',
    phone: '6139190406',
    tshirtSize: '0',
  },
  {
    fullName: 'Selena Quang',
    preferredName: 'Selena Quang',
    pronouns: '',
    year: '',
    program: 'Interactive Multimedia and Design',
    university: 'Carleton University',
    username: 'huishan.sq',
    linkedin: 'https://www.linkedin.com/in/selena-quang-0aa9422b1/',
    github: '',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Ajaan Nalliah',
    preferredName: 'Ajaan',
    pronouns: 'He/Him',
    year: 3,
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'ajaan_24',
    linkedin: 'https://www.linkedin.com/in/ajaan-nalliah',
    github: '',

    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Raaed Mirza',
    preferredName: 'Raaed Mirza',
    pronouns: '',
    year: '',
    program: 'Computer Science',
    university: 'Carleton University',
    username: 'Raaed2004',
    linkedin: 'https://linkedin.com/in/raaed-mirza-96a01324bb',
    github: 'https://github.com/Raaed-Mirza',
    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Hairuo Chen',
    preferredName: 'Hairuo Chen',
    pronouns: '',
    year: '',
    program: 'Interactive Multimedia and Design',
    university: 'Carleton University',
    username: 'emptycd',
    linkedin: 'https://www.linkedin.com/in/hairuochen',
    github: '',
    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
  {
    fullName: 'Giancarlo Salvador',
    preferredName: 'Gian',
    pronouns: '',
    year: '',
    program: 'Software Engineering',
    university: '',
    username: 'permanentbarlos',
    linkedin: 'https://www.linkedin.com/in/giancarlo-salvador-310696203/',
    github: '',
    website: '',
    instagram: '',
    allergies: '',
    phone: '',
    tshirtSize: '',
  },
]
